# Generated by Django 3.0.8 on 2020-07-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200704_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('content', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Title',
                'verbose_name_plural': 'Контент',
            },
        ),
    ]
