# Generated by Django 3.0.8 on 2020-07-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_staticpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticpage',
            options={'verbose_name': 'Страницы "О нас" и "Контакты"', 'verbose_name_plural': 'Страницы "О нас" и "Контакты"'},
        ),
        migrations.AlterField(
            model_name='enterprises',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='enterprises',
            name='phone',
            field=models.CharField(default='', max_length=100),
        ),
    ]
